//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using QFramework;
    using StupidEditor;

    public class UIPanelData : QFramework.UIPanelData
    {
    }

    public partial class UIPanel : QFramework.UIPanel
    {

        public GameObject ResourceItem;
        public Transform ScrollViewContent;
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException();
        }

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIPanelData ?? new UIPanelData();
            // please add init code here
            TypeEventRegister();
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }

        protected override void OnShow()
        {
        }

        protected override void OnHide()
        {
        }

        protected override void OnClose()
        {
        }
        private void TypeEventRegister()
        {
            TypeEventSystem.Register<FileInfo>((fileInfo) =>
            {
                var Item = Instantiate(ResourceItem, ScrollViewContent);
                Item.GetComponent<ResourceItem>().SetItemInfo(fileInfo);
                Item.GetComponent<Toggle>().group = ScrollViewContent.GetComponent<ToggleGroup>();
            });
        }
    }
}