//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Uipanel_prefab
    {
        public const string BundleName = "uipanel_prefab";
        public const string UIPANEL = "uipanel";
    }
    public class Uitodolistpanel_prefab
    {
        public const string BundleName = "uitodolistpanel_prefab";
        public const string UITODOLISTPANEL = "uitodolistpanel";
    }
}
